### ISSUE TITLE
ImagePullSecret registry value doesn't get materialized into actual .dockerconfigjson inside secret

### ISSUE THREAD

**Issue by drndos** [truecharts/library-charts#520]
### App Name

common

### SCALE Version

Not using SCALE

### App Version

N/A

### Application Events

```Shell
N/A
```

### Application Logs

```Shell
N/A
```

### Application Configuration

N/A

### Describe the bug

Currently on https://github.com/truecharts/library-charts/blob/17a84975fcabbd105a4dda301948d05770a26755/library/common/templates/lib/imagePullSecret/_createData.tpl#L24C3-L24C72 there is hardcoded "registry" instead of the actual value of $objectData.data.registry

### To Reproduce

```
imagePullSecret: 
  test:
    enabled: true
    namespace: dashy-test
    data:
      registry: "https://docker.essential-data.sk"
      username: user
      password: password
      email: no_reply@essential-data.sk
```
results in:
`{"auths":{"registry":{"auth":"xxx=","email":"no_reply@essential-data.sk","password":"password","username":"user"}}}`

### Expected Behavior

`{"auths":{"https://docker.essential-data.sk":{"auth":"xxx=","email":"no_reply@essential-data.sk","password":"password","username":"user"}}}`

### Screenshots

N/A

### Additional Context

N/A

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
