### ISSUE TITLE
home-assistant: dbUrl as a dedicated parameter for more flexibility with other pg operators

### ISSUE THREAD

**Issue by EugenMayer** [truecharts/library-charts#775]
### Is your feature request related to a problem?

When trying to run ha with a different pg operator (op) one will set

```yaml
cnpg:
  main:
    enabled: false
    # see https://www.home-assistant.io/integrations/recorder/#custom-database-engines
    creds:
      std: ${dbUrl}
```

(which is unusual enough to not be able to disable `cnpg` as usually) and use other pg connection credentials).

Doing so works until one needs to be able to use ssl, thus adding `?sslmod=required` .. doing this will make the dbUrl connection string illformatted, since this is done in the init container

```
{{- $haDBURL := (printf "%s?client_encoding=utf8" ($.Values.cnpg.main.creds.std | trimAll "\"")) }}
```

Thus `?client_encoding=utf8` will be appeneded, which will make the connection string unusable

### Describe the solution you'd like

(i'am not familiar with the expansion rules / rendering cycles in helm entirely, so this might be incorrect). 

We could introduce an additional value like
```yaml
homeassistant
  dbUrl: {{- (printf "%s?client_encoding=utf8" ($.Values.cnpg.main.creds.std | trimAll "\"")) }}
```

and then below in the init container

```yaml
....
configmap:
  init:
    enabled: true
    data:
      init.sh: |-
        #!/bin/sh
        {{ .Values.homassistant.dbUrl }}
        ...
        yq -i '.recorder.db_url = "{{ .Values.homassistant.dbUrl }}"' "$config"
        ...
      recorder.default: |-
        recorder:
          purge_keep_days: 30
          commit_interval: 3
          db_url: {{ .Values.homassistant.dbUrl }}
  ....
```

This would keep the current default while let other people easily override the dbUrl without missusing `cnpg:`
```yaml

cnpg:
  main:
    enabled: false
    # see https://www.home-assistant.io/integrations/recorder/#custom-database-engines
    creds:
      std: ${dbUrl}
```

and adds the ability to add pg connections args like `sslmode`

### Describe alternatives you've considered

-

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.
