### ISSUE TITLE
[common] traefik enableFixedMiddlewares not working

### ISSUE THREAD

**Issue by Aetylus** [truecharts/library-charts#825]
### chart Name

common

### Operating System

other

### Deployment Method

Helm

### Chart Version

navidrome 20.1.5

### Kubernetes Events

```Shell
Either a helm error:

Error: execution error at (navidrome/templates/common.yaml:1:3): Ingress - Middleware [chain-basic] is not defined in any namespace. Middleware should be created first.
helm.go:84: [debug] execution error at (navidrome/templates/common.yaml:1:3): Ingress - Middleware [chain-basic] is not defined in any namespace. Middleware should be created first.
```
Or the ingress is created with middlewares despite being disabled.

### chartlication Logs

```Shell
No container logs
```

### Chart Configuration

Disabled fixed middlewares, errors if the default `chain-basic` does not exist:
```yaml
global:
  traefik:
    enableFixedMiddlewares: false
ingress:
  main:
    enabled: true
    hosts:
      - host: navidrome.example.org
        paths:
          - path: /
            pathType: Prefix
```

Disabled fixed middlewares, set middlewares to one that exist in your cluster, still sets middlewares on the ingress:
```yaml
global:
  traefik:
    enableFixedMiddlewares: false
    fixedMiddlewares:
      - name: redirect-scheme
        namespace: kube-public
ingress:
  main:
    enabled: true
    hosts:
      - host: navidrome.example.org
        paths:
          - path: /
            pathType: Prefix
```

### Describe the bug

I believe this would appply to all charts if your ingress is traefik, but this is tested with navidrome. Attempting to disable the fixed middlewares will still result in them attempting to be parsed into the ingress.

`values.yaml`:
```yaml
global:
  traefik:
    enableFixedMiddlewares: false
ingress:
  main:
    enabled: true
    hosts:
      - host: navidrome.example.org
        paths:
          - path: /
            pathType: Prefix
```

Using this to install navidrome, you get:
```
> helm template --namespace navidrome --debug truecharts/navidrome -f values.yaml > navidrome-helm.yaml
install.go:214: [debug] Original chart version: ""
install.go:231: [debug] CHART PATH: C:\Users\<user>\AppData\Local\Temp\helm\repository\navidrome-20.1.5.tgz

Error: execution error at (navidrome/templates/common.yaml:1:3): Ingress - Middleware [chain-basic] is not defined in any namespace. Middleware should be created first.
helm.go:84: [debug] execution error at (navidrome/templates/common.yaml:1:3): Ingress - Middleware [chain-basic] is not defined in any namespace. Middleware should be created first.
```

Even if you replace the `fixedMiddlewares` with an existing middleware, such that it won't error:
```yaml
global:
  traefik:
    enableFixedMiddlewares: false
    fixedMiddlewares:
      - name: redirect-scheme
        namespace: kube-public
ingress:
  main:
    enabled: true
    hosts:
      - host: navidrome.example.org
        paths:
          - path: /
            pathType: Prefix
```
The middleware is still attached to the ingress despite being marked as disabled:
```yaml
# ... Truncate non-ingress
# Source: navidrome/templates/common.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-navidrome
  namespace: navidrome
  labels:
    app: "navidrome-20.1.5"
    app.kubernetes.io/instance: "release-name"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "navidrome"
    app.kubernetes.io/version: "0.52.5"
    helm-revision: "1"
    helm.sh/chart: "navidrome-20.1.5"
    release: "release-name"
  annotations:
    # .. Truncate checksums
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "kube-public-redirect-scheme@kubernetescrd"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: 
  rules:
    - host: "navidrome.example.org"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: release-name-navidrome
                port:
                  number: 4533
```

The only way to get around this seems to be by setting the `fixedMiddlewares` to an empty list, regardless of whether its enabled or not:
```yaml
global:
  traefik:
    fixedMiddlewares: []
ingress:
  main:
    enabled: true
    hosts:
      - host: navidrome.example.org
        paths:
          - path: /
            pathType: Prefix
```

### To Reproduce

1. Create a `values.yaml` that matches one of the two that have `enableFixedMiddlewares: false`.
2. Run `helm template --namespace navidrome --debug truecharts/navidrome -f values.yaml`

### Expected Behavior

I expect that setting `enableFixedMiddlewares: false` would ignore the default fixed middleware existing or not. I would also expect that if the fixed middlewares _do_ exist, that disabling them would not apply the annotation.

### Screenshots

No screenshots

### Additional Context

No additional context

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] I've understand TrueNAS SCALE Apps are deprecated and TrueCharts does not accept TrueNAS SCALE related issues
- [X] I've prefixed my issue title with `[Chart-Name]`
