### ISSUE TITLE
[qbittorrent] Pod fails to start due to configMap volume mismatch

### ISSUE THREAD

**Issue by eliminyro** [truecharts/library-charts#842]
### chart Name

qbittorrent

### Operating System

other

### Deployment Method

ArgoCD

### Chart Version

21.1.1

### Kubernetes Events

```Shell
22s (x34 over 53m)      Warning   FailedMount            Pod/qbittorrent-64bfbcccf7-v84rw                 MountVolume.SetUp failed for volume "vpnscripts" : configmap "vpnscripts" not found
```

### chartlication Logs

```Shell
No log because containers are not up due to the issue with the volume mentioned.
```

### Chart Configuration

```yaml
    qbitportforward:
      enabled: true
      QBT_USERNAME: "REDACTED"
      QBT_PASSWORD: "REDACTED"
    persistence:
      REDACTED:

    TZ: "REDACTED"

    addons:
      vpn:
        type: gluetun
        killSwitch: true
        env:
          VPN_SERVICE_PROVIDER: "REDACTED"
          SERVER_REGIONS: "REDACTED"
          PORT_FORWARD_ONLY: true
          DNS_KEEP_NAMESERVER: "on"
          UPDATER_PERIOD: "24h"
          EXTRA_SUBNETS: "10.43.0.0/16"
        scripts:
          up: |-
            #!/bin/sh
            curl -s -b REDACTED
```

### Describe the bug

Reference name in the volume that mounts vpn configmap is incorrect.
Chart creates 'qbittorrent-vpnscripts' configMap while it is referenced as just 'vpnscripts'

### To Reproduce

1. prepare the minimal set of values for the chart (including VPN addon)
2. Specify scripts.up value for the script launched after VPN is started.
3. Check the pod events.

### Expected Behavior

configMap name and the reference name in the volume correspond.

### Screenshots

![Greenshot 2024-06-23 13 25 24](https://github.com/truecharts/library-charts/assets/22568873/8fb30505-d7fb-4327-9dff-6973e50df902)
Here is a screenshot of configMap resource in ArgoCD.
![Greenshot 2024-06-23 13 27 00](https://github.com/truecharts/library-charts/assets/22568873/02097b55-30fb-4410-a332-7955b3e117b8)
And here is a screenshot of the reference name in the volume.

### Additional Context

I see that the reference name 'vpnscripts' is actually hardcoded in volume template for VPN addon [here](https://github.com/truecharts/library-charts/blob/main/library/common/templates/addons/vpn/_volume.tpl#L8).
Perhaps, that is the main reason for the misalignment.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] I've understand TrueNAS SCALE Apps are deprecated and TrueCharts does not accept TrueNAS SCALE related issues
- [X] I've prefixed my issue title with `[Chart-Name]`
