### ISSUE TITLE
jellfyfin - Bug in wiki workload resources

### ISSUE THREAD

**Issue by djtecha** [truecharts/library-charts#855]
### chart Name

common

### Operating System

other

### Deployment Method

Helm

### Chart Version

Jellyfin 20.1.13

### Kubernetes Events

```Shell
Fails to allocate pod
```

### chartlication Logs

```Shell
Fails to allocate pod
```

### Chart Configuration

```
workload:
  workload-name:
    podSpec:
      containers:
        container-name:
          resources:
            limits:
              intel.com/i915: 1
```

### Describe the bug

the wiki uses this reference:

```
workload:
  workload-name:
    podSpec:
      containers:
        container-name:
          resources:
            limits:
              intel.com/i915: 1
```
but the resource limit is actually 

```
gpu.intel.com/i915: 1
```

Not sure if this is a version change but looks like a type on the wiki

### To Reproduce

Use the wrong helm key name

### Expected Behavior

The Pod should launch on the node with the intel gpu.

### Screenshots

NA

### Additional Context

BA

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] I've understand TrueNAS SCALE Apps are deprecated and TrueCharts does not accept TrueNAS SCALE related issues
- [X] I've prefixed my issue title with `[Chart-Name]`
